cache: bundler
sudo: false
before_script:
  - psql -c 'create database curator_test;' -U postgres
language: ruby
rvm:
  - "2.2.3"
addons:
  postgresql: "9.3"
script:
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
